-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

USE CATALOG `dbdemos_vishesh`;
USE SCHEMA `contest_mock`;

SELECT * from wallet_tx;

-- COMMAND ----------

SELECT * from contests;

-- COMMAND ----------

SELECT * from contests_tx;

-- COMMAND ----------

SELECT * from users;

-- COMMAND ----------

select c.contest_sport, u.origin_state, count(distinct u.user_id) as user_count
from users u
left join contests_tx ct on u.user_id = ct.user_id
left join contests c on ct.contest_id = c.contest_id
group by all
order by all

-- COMMAND ----------


